"""Sinema Laboratuvari: 30 sinematik gorunum.

Her gorunum renk, kontrast, parlak alan gecisi ve dokuyu *birlikte*
kurar; yalnizca LUT veya siyah bant degildir. Adlar yaratici yonu
tarif eder; ticari LUT paketleri, tescilli preset dosyalari veya film
stoku emulsiyonlarinin birebir kopyasi degildir.

Bicim: (kimlik, ad, amac, aciklama, [(islem_id, {parametreler}), ...])
"""
from __future__ import annotations

PresetDef = tuple[str, str, str, str, list[tuple[str, dict]]]


CINEMA: list[PresetDef] = [
    ("teal-amber", "Teal & Amber", "Aksiyon, portre, genel",
     "Soguk golgeler, sicak parlak alanlar. Modern sinemanin en yaygin "
     "renk ayrimi; tenler sicak kalirken cevre serinler.",
     [("color.grading", {"shadow_color": [0.32, 0.50, 0.58],
                         "shadow_amount": 44,
                         "midtone_color": [0.52, 0.50, 0.48],
                         "midtone_amount": 12,
                         "highlight_color": [0.66, 0.54, 0.38],
                         "highlight_amount": 40, "preserve_luma": True}),
      ("film.tone_curve", {"toe": 26, "shoulder": 34, "strength": 14}),
      ("color.vibrance", {"amount": 14, "protect_skin": True}),
      ("texture.grain", {"amount": 16, "size": 1.8})]),

    ("soft-blockbuster", "Soft Blockbuster", "Genel, kalabalik sahne",
     "Kontrollu kontrast ve yumusak renk ayrimi; gozu yormayan, genis "
     "kitleye yonelik sinema bakisi.",
     [("film.tone_curve", {"toe": 30, "shoulder": 50, "strength": 22}),
      ("color.grading", {"shadow_color": [0.38, 0.48, 0.60],
                         "shadow_amount": 34,
                         "highlight_color": [0.62, 0.55, 0.44],
                         "highlight_amount": 32}),
      ("light.halation", {"threshold": 0.70, "radius": 40, "intensity": 38}),
      ("detail.clarity", {"amount": 16, "radius": 80}),
      ("texture.grain", {"amount": 12, "size": 1.6})]),

    ("desert-epic", "Desert Epic", "Col, genis manzara",
     "Kum, altin ve bakir tonlari; genis manzaranin sicak destani.",
     [("color.white_balance", {"kelvin": 5200, "tint": 8}),
      ("color.grading", {"shadow_color": [0.46, 0.44, 0.42],
                         "shadow_amount": 22,
                         "highlight_color": [0.68, 0.56, 0.36],
                         "highlight_amount": 42}),
      ("color.hsl", {"orange_sat": 32, "yellow_sat": 28, "blue_lum": -32,
                     "blue_sat": -26}),
      ("film.tone_curve", {"toe": 12, "shoulder": 34, "strength": 34}),
      ("detail.clarity", {"amount": 32, "radius": 100}),
      ("light.halation", {"threshold": 0.72, "radius": 36, "intensity": 30})]),

    ("neon-rain", "Neon Rain", "Gece sehri, yagmur",
     "Mavi ve magenta gece atmosferi; islak yuzeylerde parlayan neon.",
     [("color.grading", {"shadow_color": [0.32, 0.40, 0.70],
                         "shadow_amount": 46,
                         "highlight_color": [0.68, 0.40, 0.64],
                         "highlight_amount": 34}),
      ("light.bloom", {"threshold": 0.6, "radius": 120, "intensity": 58}),
      ("light.halation", {"threshold": 0.7, "radius": 38, "intensity": 34,
                          "color": [0.9, 0.35, 0.75]}),
      ("light.anamorphic", {"threshold": 0.82, "length": 300, "thickness": 6,
                            "intensity": 38}),
      ("texture.grain", {"amount": 18, "size": 2.0})]),

    ("emerald-thriller", "Emerald Thriller", "Gerilim, ic mekan",
     "Yesil golgeler ve tedirgin edici sogukluk.",
     [("color.grading", {"shadow_color": [0.38, 0.56, 0.44],
                         "shadow_amount": 44,
                         "midtone_color": [0.48, 0.52, 0.48],
                         "midtone_amount": 20,
                         "highlight_color": [0.56, 0.56, 0.50],
                         "highlight_amount": 18}),
      ("color.saturation", {"amount": -14}),
      ("film.tone_curve", {"toe": 20, "shoulder": 30, "strength": 22}),
      ("lens.vignette", {"amount": -22, "midpoint": 0.6})]),

    # Sokak kategorisindeki "Urban Steel" ile ayni celik-mavisi ailede.
    # Ayrim kasitli: bu sinematik surum daha derin, ayagi ezik ve film
    # egrili; sokak surumu daha notr ve dokuludur.
    ("steel-thriller", "Steel Thriller", "Gerilim, sehir",
     "Sinematik celik mavisi: ezik ayak, soguk golge, sikismis parlak "
     "alan. Gerilim filmlerinin mesafeli bakisi.",
     [("film.tone_curve", {"toe": 46, "shoulder": 38, "strength": 20}),
      ("color.grading", {"shadow_color": [0.34, 0.44, 0.64],
                         "shadow_amount": 58,
                         "midtone_color": [0.46, 0.49, 0.55],
                         "midtone_amount": 22,
                         "highlight_color": [0.52, 0.55, 0.60],
                         "highlight_amount": 30}),
      ("color.saturation", {"amount": -34}),
      ("tone.contrast", {"amount": 30}),
      ("lens.vignette", {"amount": -26, "midpoint": 0.55})]),

    ("classic-noir", "Classic Noir", "Gece, portre, gerilim",
     "Guclu siyah-beyaz ayrim: derin golgeler, sert isik.",
     [("color.monochrome", {"amount": 100, "red": 14, "blue": -22}),
      ("tone.curves", {"rgb": [[0, 0], [0.36, 0.15], [0.76, 0.87], [1, 1]]}),
      ("lens.vignette", {"amount": -44, "midpoint": 0.5, "feather": 0.8}),
      ("texture.grain", {"amount": 30, "size": 2.4})]),

    ("silver-screen", "Silver Screen", "Klasik portre",
     "Yumusak klasik siyah-beyaz; genis ton araligi ve parlak hale.",
     [("color.monochrome", {"amount": 100, "orange": 12, "yellow": 8}),
      ("film.tone_curve", {"toe": 34, "shoulder": 46, "strength": 8}),
      ("light.bloom", {"threshold": 0.7, "radius": 100, "intensity": 34}),
      ("texture.grain", {"amount": 20, "size": 2.0})]),

    ("bleach-drama", "Bleach Drama", "Savas, dram",
     "Dusuk doygunluk ve guclu kontrast; agartma atlanmis film.",
     [("tone.shadows_highlights", {"highlights": -26}),
      ("style.bleach_bypass", {"strength": 70, "contrast": 32, "grit": 30,
                               "amount": 100}),
      ("color.grading", {"shadow_color": [0.44, 0.48, 0.52],
                         "shadow_amount": 22}),
      ("texture.grain", {"amount": 28, "size": 2.2})]),

    ("golden-memory", "Golden Memory", "Geriye donus, aile",
     "Sicak, nostaljik ve yumusak; hatira hissi.",
     [("color.white_balance", {"kelvin": 4700, "tint": 14}),
      ("color.grading", {"highlight_color": [0.70, 0.57, 0.38],
                         "highlight_amount": 46,
                         "shadow_color": [0.54, 0.47, 0.40],
                         "shadow_amount": 30}),
      ("tone.fade", {"lift": 34, "rolloff": 20, "amount": 100}),
      ("color.saturation", {"amount": -18}),
      ("texture.grain", {"amount": 30, "size": 2.8, "colour": True}),
      ("lens.vignette", {"amount": -20, "midpoint": 0.62})]),

    ("pastel-cinema", "Pastel Cinema", "Bagimsiz film, komedi",
     "Hafif kontrast ve pastel palet; simetrik, oyuncu bir bakis.",
     [("color.saturation", {"amount": -38}),
      ("color.grading", {"midtone_color": [0.59, 0.49, 0.55],
                         "midtone_amount": 40,
                         "highlight_color": [0.61, 0.56, 0.45],
                         "highlight_amount": 34,
                         "shadow_color": [0.53, 0.50, 0.57],
                         "shadow_amount": 26}),
      ("tone.fade", {"lift": 28, "rolloff": 24, "amount": 100}),
      ("light.diffusion", {"strength": 26, "radius": 60, "lift": 18}),
      ("film.tone_curve", {"toe": 32, "shoulder": 42, "strength": -14})]),

    ("winter-drama", "Winter Drama", "Kis, dram",
     "Soguk, acik ve sakin tonlar; nefes alan bir bosluk.",
     [("color.white_balance", {"kelvin": 7400, "tint": -8}),
      ("color.saturation", {"amount": -24}),
      ("tone.shadows_highlights", {"shadows": 26, "highlights": -22}),
      ("color.grading", {"shadow_color": [0.42, 0.48, 0.60],
                         "shadow_amount": 30}),
      ("light.diffusion", {"strength": 18, "radius": 70, "lift": 22})]),

    ("nordic-mystery", "Nordic Mystery", "Polisiye, kuzey",
     "Soluk renkler ve serin golgeler; iskandinav polisiyesi.",
     [("color.saturation", {"amount": -52}),
      ("color.grading", {"shadow_color": [0.44, 0.52, 0.56],
                         "shadow_amount": 30,
                         "midtone_color": [0.50, 0.53, 0.53],
                         "midtone_amount": 26}),
      ("tone.fade", {"lift": 38, "rolloff": 22, "amount": 100}),
      ("film.tone_curve", {"toe": 44, "shoulder": 30, "strength": -6}),
      ("texture.grain", {"amount": 26, "size": 2.6})]),

    ("vintage-western", "Vintage Western", "Western, donem filmi",
     "Toprak ve sicak tozlu tonlar; guneste solmus gorunum.",
     [("color.white_balance", {"kelvin": 5300, "tint": 12}),
      ("color.hsl", {"orange_sat": 18, "yellow_hue": -14, "blue_sat": -30}),
      ("color.grading", {"shadow_color": [0.50, 0.46, 0.38],
                         "shadow_amount": 30,
                         "highlight_color": [0.66, 0.58, 0.44],
                         "highlight_amount": 34}),
      ("tone.fade", {"lift": 18, "rolloff": 12, "amount": 100}),
      ("texture.dust", {"dust": 20, "scratches": 14, "amount": 100})]),

    ("night-tungsten", "Night Tungsten", "Gece ic mekan",
     "Sicak yapay isiklar, serin gece cevresi.",
     [("color.white_balance", {"kelvin": 4100, "tint": 12}),
      ("color.grading", {"highlight_color": [0.74, 0.55, 0.30],
                         "highlight_amount": 54,
                         "shadow_color": [0.33, 0.42, 0.66],
                         "shadow_amount": 46}),
      ("light.halation", {"threshold": 0.62, "radius": 44, "intensity": 54}),
      ("tone.shadows_highlights", {"shadows": 32, "highlights": -26}),
      ("color.saturation", {"amount": -14}),
      ("texture.grain", {"amount": 24, "size": 2.2})]),

    ("moonlit-blue", "Moonlit Blue", "Gece dis mekan",
     "Mavi gece yorumu. Gercek yeniden aydinlatma degildir; renk ve ton "
     "yorumudur.",
     [("color.white_balance", {"kelvin": 8200, "tint": -10}),
      ("tone.exposure", {"stops": -0.3}),
      ("color.grading", {"shadow_color": [0.34, 0.42, 0.66],
                         "shadow_amount": 46,
                         "midtone_color": [0.42, 0.48, 0.62],
                         "midtone_amount": 28}),
      ("tone.curves", {"rgb": [[0, 0], [0.4, 0.28], [0.8, 0.82], [1, 0.96]]}),
      ("texture.grain", {"amount": 24, "size": 2.2})]),

    ("urban-crime", "Urban Crime", "Polisiye, sehir gecesi",
     "Kirli yesil, amber ve siki kontrast.",
     [("color.grading", {"shadow_color": [0.44, 0.52, 0.42],
                         "shadow_amount": 38,
                         "highlight_color": [0.64, 0.54, 0.40],
                         "highlight_amount": 32}),
      ("style.bleach_bypass", {"strength": 40, "contrast": 24, "grit": 20,
                               "amount": 70}),
      ("tone.contrast", {"amount": 20}),
      ("texture.grain", {"amount": 26, "size": 2.4})]),

    ("indie-matte", "Indie Matte", "Bagimsiz film",
     "Kalkik siyahlar ve dusuk doygunluk; mat, sakin bir bakis.",
     [("tone.fade", {"lift": 46, "rolloff": 28, "amount": 100}),
      ("color.saturation", {"amount": -34}),
      ("color.grading", {"shadow_color": [0.45, 0.50, 0.60],
                         "shadow_amount": 38,
                         "midtone_color": [0.50, 0.51, 0.56],
                         "midtone_amount": 22}),
      ("film.tone_curve", {"toe": 48, "shoulder": 36, "strength": -12}),
      ("texture.grain", {"amount": 44, "size": 3.0, "colour": True})]),

    ("festival-natural", "Festival Natural", "Festival filmi, dram",
     "Olculu renk ve dogal tenler; mudahalenin fark edilmedigi bakis.",
     [("film.tone_curve", {"toe": 16, "shoulder": 30, "strength": 22}),
      ("tone.black_white_point", {"black": 12, "white": 8}),
      ("color.grading", {"shadow_color": [0.49, 0.51, 0.53],
                         "shadow_amount": 16,
                         "highlight_color": [0.57, 0.53, 0.46],
                         "highlight_amount": 24}),
      ("color.vibrance", {"amount": 26, "protect_skin": True}),
      ("detail.clarity", {"amount": 26, "radius": 70}),
      ("texture.grain", {"amount": 12, "size": 1.6})]),

    # "Dream Haze" (isik kategorisi) ayni yumusaklik ailesinde. Ayrim:
    # bu sinematik surum menekse kaymasi, halation ve guclu bloom ile
    # *gercek disi* durur; Dream Haze notr ve atmosferik kalir.
    ("dream-sequence", "Dream Sequence", "Ruya, geriye donus",
     "Menekse kaymali guclu bloom ve halation: gecmise donus "
     "sahnelerinin gercek disi parlamasi.",
     [("tone.shadows_highlights", {"highlights": -48, "shadows": 18}),
      ("light.diffusion", {"strength": 52, "radius": 120, "lift": 42}),
      ("light.bloom", {"threshold": 0.58, "radius": 220, "intensity": 66}),
      ("light.halation", {"amount": 34, "threshold": 0.66, "radius": 90}),
      ("color.saturation", {"amount": -24}),
      ("tone.fade", {"lift": 30, "rolloff": 24, "amount": 100}),
      ("color.grading", {"highlight_color": [0.58, 0.54, 0.58],
                         "highlight_amount": 24})]),

    ("romantic-diffusion", "Romantic Diffusion", "Romantik, portre",
     "Yumusak isik ve sicak tenler; klasik romantik sahne.",
     [("tone.shadows_highlights", {"highlights": -32}),
      ("light.diffusion", {"strength": 58, "radius": 95, "lift": 34}),
      ("light.bloom", {"threshold": 0.74, "radius": 130, "intensity": 38}),
      ("color.white_balance", {"kelvin": 5300, "tint": 6}),
      ("color.grading", {"highlight_color": [0.60, 0.53, 0.47],
                         "highlight_amount": 26,
                         "midtone_color": [0.54, 0.50, 0.50],
                         "midtone_amount": 18}),
      ("light.halation", {"threshold": 0.68, "radius": 36, "intensity": 38}),
      ("tone.contrast", {"amount": -18})]),

    ("bronze-action", "Bronze Action", "Aksiyon",
     "Bronz parlak alanlar ve koyu golgeler; sert ve metalik.",
     [("color.grading", {"shadow_color": [0.42, 0.44, 0.48],
                         "shadow_amount": 26,
                         "highlight_color": [0.68, 0.56, 0.38],
                         "highlight_amount": 42}),
      ("style.bleach_bypass", {"strength": 44, "contrast": 30, "grit": 28,
                               "amount": 80}),
      ("detail.clarity", {"amount": 26, "radius": 60}),
      ("lens.vignette", {"amount": -24, "midpoint": 0.62})]),

    ("ocean-suspense", "Ocean Suspense", "Deniz, gerilim",
     "Cyan ve mavi agirlikli gerilim; derinlik ve sogukluk.",
     [("color.channel_mixer", {"rr": 74, "rg": 10, "rb": 16,
                               "gg": 100, "gb": 10,
                               "br": -6, "bb": 112, "amount": 100}),
      ("color.grading", {"shadow_color": [0.26, 0.50, 0.62],
                         "shadow_amount": 54,
                         "midtone_color": [0.38, 0.50, 0.58],
                         "midtone_amount": 32,
                         "highlight_color": [0.44, 0.52, 0.56],
                         "highlight_amount": 22}),
      ("color.hsl", {"aqua_sat": 30, "blue_sat": 24, "orange_sat": -46,
                     "red_sat": -34}),
      ("tone.exposure", {"stops": -0.25}),
      ("film.tone_curve", {"toe": 18, "shoulder": 24, "strength": 26}),
      ("lens.vignette", {"amount": -30, "midpoint": 0.58})]),

    ("crimson-night", "Crimson Night", "Gerilim, korku",
     "Kirmizi isik vurgulu koyu atmosfer.",
     [("color.grading", {"shadow_color": [0.56, 0.36, 0.40],
                         "shadow_amount": 38,
                         "highlight_color": [0.70, 0.44, 0.40],
                         "highlight_amount": 34}),
      ("tone.curves", {"rgb": [[0, 0], [0.38, 0.22], [0.78, 0.84], [1, 1]]}),
      ("light.halation", {"threshold": 0.7, "radius": 42, "intensity": 40,
                          "color": [1.0, 0.28, 0.20]}),
      ("lens.vignette", {"amount": -34, "midpoint": 0.55}),
      ("texture.grain", {"amount": 26, "size": 2.2})]),

    ("olive-war-drama", "Olive War Drama", "Savas, donem",
     "Mat zeytin ve toprak renkleri; tozlu ve agir.",
     [("color.hsl", {"green_hue": 14, "green_sat": -22, "yellow_hue": -12,
                     "blue_sat": -26}),
      ("style.bleach_bypass", {"strength": 56, "contrast": 28, "grit": 32,
                               "amount": 90}),
      ("color.grading", {"midtone_color": [0.50, 0.52, 0.44],
                         "midtone_amount": 30}),
      ("texture.dust", {"dust": 24, "scratches": 12, "amount": 100}),
      ("texture.grain", {"amount": 30, "size": 2.6})]),

    ("retro-scifi", "Retro Sci-Fi", "Bilim kurgu, retro",
     "Cyan/amber renk ayrimi ve analog doku; 70-80'ler bilim kurgusu.",
     [("color.lut3d", {"lut": "builtin:teal_amber", "amount": 85}),
      ("color.grading", {"shadow_color": [0.30, 0.52, 0.60],
                         "shadow_amount": 34,
                         "highlight_color": [0.68, 0.56, 0.36],
                         "highlight_amount": 30}),
      ("light.anamorphic", {"threshold": 0.8, "length": 320, "thickness": 6,
                            "intensity": 40}),
      ("light.halation", {"threshold": 0.72, "radius": 40, "intensity": 34}),
      ("texture.grain", {"amount": 50, "size": 3.4, "colour": True}),
      ("lens.chromatic_aberration", {"amount": 48}),
      ("texture.dust", {"dust": 18, "scratches": 12, "amount": 100})]),

    ("16mm-diary", "16mm Diary", "Gunluk, belgesel",
     "Belirgin grain ve yumusak ayrinti; kucuk format film hissi.",
     [("texture.grain", {"amount": 64, "size": 3.4, "roughness": 62,
                         "colour": True}),
      ("film.tone_curve", {"toe": 34, "shoulder": 40, "strength": 12}),
      ("light.diffusion", {"strength": 20, "radius": 50, "lift": 20}),
      ("color.saturation", {"amount": -12}),
      ("lens.vignette", {"amount": -18, "midpoint": 0.66})]),

    ("35mm-warm-print", "35mm Warm Print", "Genel, portre",
     "Sicak baski benzeri ton gecisi; yumusak omuz ve kehribar parlaklik.",
     [("film.tone_curve", {"toe": 34, "shoulder": 52, "strength": 12}),
      ("color.white_balance", {"kelvin": 4900, "tint": 12}),
      ("color.grading", {"highlight_color": [0.70, 0.56, 0.38],
                         "highlight_amount": 42,
                         "shadow_color": [0.52, 0.48, 0.44],
                         "shadow_amount": 26}),
      ("color.hsl", {"orange_sat": 16, "yellow_sat": 12, "blue_sat": -18}),
      ("light.halation", {"threshold": 0.70, "radius": 34, "intensity": 34}),
      ("texture.grain", {"amount": 22, "size": 2.0, "colour": True})]),

    ("35mm-cool-print", "35mm Cool Print", "Genel, sehir",
     "Serin baski benzeri ton gecisi; mavi golge, notr parlaklik.",
     [("film.tone_curve", {"toe": 26, "shoulder": 42, "strength": 18}),
      ("color.white_balance", {"kelvin": 8000, "tint": -14}),
      ("color.grading", {"shadow_color": [0.36, 0.46, 0.66],
                         "shadow_amount": 42,
                         "highlight_color": [0.48, 0.52, 0.58],
                         "highlight_amount": 26}),
      ("color.hsl", {"blue_sat": 18, "aqua_sat": 14, "orange_sat": -20}),
      ("texture.grain", {"amount": 22, "size": 2.0, "colour": True})]),

    ("monochrome-documentary", "Monochrome Documentary", "Belgesel, haber",
     "Dogal kontrastli, grenli belgesel siyah-beyaz.",
     [("color.monochrome", {"amount": 100, "red": 8, "orange": 10,
                            "blue": -12}),
      ("film.tone_curve", {"toe": 26, "shoulder": 34, "strength": 14}),
      ("texture.grain", {"amount": 46, "size": 2.6, "roughness": 58}),
      ("detail.clarity", {"amount": 18, "radius": 60})]),
]
