"""Turkce diyakritik sozlugu: ASCII yazim -> dogru yazim.

Neden gerekli: proje kaynak *yorumlarini* kasitli olarak ASCII tutuyor
(kodlama sorunlarina karsi), ama **kullaniciya gorunen metinler** dogru
Turkce olmali. Bu sozluk yalnizca kullaniciya gorunen dizgilerde
kullanilir; tanimlayicilara ve yorumlara dokunulmaz.

Yalnizca diyakritik gerektiren kelimeler burada. "renk", "ton", "alan",
"nokta" gibi zaten dogru yazilan kelimeler listede yoktur.
"""
from __future__ import annotations

import re

#: kucuk harfli ASCII yazim -> dogru Turkce yazim
WORDS: dict[str, str] = {
    # --- fiiller ve ekli bicimleri ---
    "acar": "açar", "acida": "açıda", "acidan": "açıdan", "aciklama": "açıklama",
    "acikken": "açıkken", "acilamadi": "açılamadı", "acilista": "açılışta",
    "acin": "açın", "acisini": "açısını", "acmadiniz": "açmadınız",
    "actigi": "açtığı", "adi": "adı", "adiminin": "adımının", "adina": "adına",
    "agartma": "ağartma", "agirlikli": "ağırlıklı",
    "agirliklari": "ağırlıkları", "agirliklariyla": "ağırlıklarıyla",
    "aktarilamadi": "aktarılamadı", "aktarilan": "aktarılan",
    "aktarin": "aktarın", "alanlari": "alanları", "alanlarin": "alanların",
    "algilama": "algılama", "algisal": "algısal", "alinabilir": "alınabilir",
    "alinamaz": "alınamaz", "alinani": "alınanı", "altindaki": "altındaki",
    "araligina": "aralığına", "araligindaki": "aralığındaki",
    "araligini": "aralığını", "araliginin": "aralığının",
    "araliklar": "aralıklar", "arasinda": "arasında",
    "arasindaki": "arasındaki", "arasi": "arası",
    "arac": "araç", "aracidir": "aracıdır", "artirir": "artırır",
    "artirmadan": "artırmadan", "artan": "artan", "asagi": "aşağı",
    "asil": "asıl", "atlandi": "atlandı", "atlanmasi": "atlanması",
    "ayari": "ayarı", "ayarlanabilir": "ayarlanabilir",
    "ayarlanir": "ayarlanır", "ayarlari": "ayarları",
    "ayarlarin": "ayarların", "ayarlarini": "ayarlarını",
    "aydinlatir": "aydınlatır", "ayiran": "ayıran", "ayni": "aynı",
    "ayri": "ayrı", "ayrilir": "ayrılır", "ayrilma": "ayrılma",
    "ayrimi": "ayrımı", "ayrimini": "ayrımını", "ayriminin": "ayrımının",
    "ayrinti": "ayrıntı", "ayrintisi": "ayrıntısı",
    "ayrintisini": "ayrıntısını", "azaltarak": "azaltarak",
    "azaltir": "azaltır",
    "bagimsiz": "bağımsız", "bakisi": "bakışı", "basarisiz": "başarısız",
    "basarili": "başarılı", "basilmis": "basılmış", "basina": "başına",
    "baski": "baskı", "basladigi": "başladığı", "baslangic": "başlangıç",
    "baslayan": "başlayan", "basin": "basın",
    "bastirilabilir": "bastırılabilir", "bastirma": "bastırma",
    "belirginlestirir": "belirginleştirir", "belirginligi": "belirginliği",
    "beneklerin": "beneklerin", "benekleri": "benekleri",
    "beyazi": "beyazı", "beyazlari": "beyazları",
    "bicim": "biçim", "bileseni": "bileşeni", "birakin": "bırakın",
    "birakmaz": "bırakmaz", "biraktigi": "bıraktığı",
    "bolge": "bölge", "bolgelerinin": "bölgelerinin",
    "bos": "boş", "boyledir": "böyledir", "boyutu": "boyutu",
    "boyutunu": "boyutunu", "bozmaz": "bozmaz",
    "bulanik": "bulanık", "bulaniklik": "bulanıklık",
    "bulunamadi": "bulunamadı", "bulundu": "bulundu",
    "buyuk": "büyük",
    "calisir": "çalışır", "canliligini": "canlılığını",
    "canlilik": "canlılık", "carpim": "çarpım", "ceker": "çeker",
    "cevirir": "çevirir", "cevresinde": "çevresinde", "cift": "çift",
    "cikar": "çıkar", "cikarir": "çıkarır", "cikti": "çıktı",
    "ciktiya": "çıktıya", "cinsinden": "cinsinden", "cizgi": "çizgi",
    "cizgisi": "çizgisi", "cizik": "çizik", "cizikler": "çizikler",
    "cok": "çok", "cozumlenemedi": "çözümlenemedi",
    "cozunurluk": "çözünürlük", "cozunurlukten": "çözünürlükten",
    "cunku": "çünkü",
    "dagilimi": "dağılımı", "dagilimini": "dağılımını",
    "dagilir": "dağılır", "deger": "değer", "degeri": "değeri",
    "degil": "değil", "degisimler": "değişimler", "degismis": "değişmiş",
    "degistirildi": "değiştirildi", "degistirin": "değiştirin",
    "degistirir": "değiştirir", "degistirme": "değiştirme",
    "degistirmesin": "değiştirmesin", "degistirmez": "değiştirmez",
    "dengesi": "dengesi", "dengesini": "dengesini",
    "derinlik": "derinlik", "deseni": "deseni", "destegi": "desteği",
    "desteklenmiyor": "desteklenmiyor", "deyin": "deyin",
    "digerine": "diğerine", "disa": "dışa", "disaridan": "dışarıdan",
    "disinda": "dışında", "dogru": "doğru",
    "dokunur": "dokunur", "dokusu": "dokusu", "dokuyu": "dokuyu",
    "dondugu": "döndüğü", "dondurur": "döndürür", "donmesi": "dönmesi",
    "donusumu": "dönüşümü", "dosyalari": "dosyaları",
    "dosyanizi": "dosyanızı", "dosyasi": "dosyası",
    "dosyasina": "dosyasına", "dosyasinin": "dosyasının",
    "doygun": "doygun", "doygunlastirir": "doygunlaştırır",
    "doygunluk": "doygunluk", "doyum": "doyum", "doyumu": "doyumu",
    "duser": "düşer", "dusuk": "düşük", "dusurme": "düşürme",
    "dusurmek": "düşürmek", "dusuruldu": "düşürüldü",
    "dusurur": "düşürür", "duz": "düz", "duzenle": "düzenle",
    "duzenleyici": "düzenleyici", "duzensiz": "düzensiz",
    "duzenlenmis": "düzenlenmiş", "duotone": "duotone",
    "edilebilir": "edilebilir", "edilmez": "edilmez",
    "egri": "eğri", "egrileri": "eğrileri", "egrisi": "eğrisi",
    "egrisinde": "eğrisinde", "egrisini": "eğrisini", "egriyi": "eğriyi",
    "egriye": "eğriye", "eklemez": "eklemez", "eklendi": "eklendi",
    "eklenemedi": "eklenemedi", "ekleyin": "ekleyin",
    "ekrana": "ekrana", "elips": "elips",
    "emulsiyonunun": "emülsiyonunun", "engeller": "engeller",
    "esik": "eşik", "esit": "eşit", "esler": "eşler",
    "eski": "eski", "estetigi": "estetiği", "etikete": "etikete",
    "etkilemez": "etkilemez", "etkilenen": "etkilenen",
    "etkilenir": "etkilenir", "etkiler": "etkiler", "etkin": "etkin",
    "etkisi": "etkisi", "etkisinin": "etkisinin", "etkisiz": "etkisiz",
    "etkinin": "etkinin", "etmenin": "etmenin", "etmesi": "etmesi",
    "etmeyi": "etmeyi", "etrafinda": "etrafında", "ezilmez": "ezilmez",
    "farki": "farkı", "farkin": "farkın", "farkli": "farklı",
    "favoriler": "favoriler", "favorileri": "favorileri",
    "filmde": "filmde", "filmi": "filmi", "filmin": "filmin",
    "filtrele": "filtrele", "filtresinin": "filtresinin",
    "fotograf": "fotoğraf", "fotografa": "fotoğrafa",
    "fotografi": "fotoğrafı", "fotograflar": "fotoğraflar",
    "fotograflari": "fotoğrafları",
    "gecis": "geçiş", "gecisi": "geçişi", "gecisler": "geçişler",
    "gecisli": "geçişli", "gecici": "geçici", "gecmis": "geçmiş",
    "genisligi": "genişliği", "genis": "geniş", "gercek": "gerçek",
    "gercekten": "gerçekten", "gerekli": "gerekli",
    "getirir": "getirir", "giris": "giriş", "gokyuzu": "gökyüzü",
    "golge": "gölge", "golgeler": "gölgeler", "golgelerde": "gölgelerde",
    "golgelere": "gölgelere", "golgeleri": "gölgeleri",
    "golgelerin": "gölgelerin", "golgeye": "gölgeye",
    "gomulu": "gömülü", "gore": "göre", "gormek": "görmek",
    "goruntu": "görüntü", "goruntude": "görüntüde",
    "goruntunun": "görüntünün", "goruntuye": "görüntüye",
    "goruntuyu": "görüntüyü", "gorunen": "görünen",
    "gorunum": "görünüm", "gorunumler": "görünümler",
    "gorunumlerim": "görünümlerim", "gorunumu": "görünümü",
    "gorunumum": "görünümüm", "gorunumun": "görünümün",
    "gorunur": "görünür", "goster": "göster",
    "gosterimi": "gösterimi", "gosterir": "gösterir", "goze": "göze",
    "guclu": "güçlü", "gumus": "gümüş", "gunluk": "günlük",
    "gurultusu": "gürültüsü", "gurultuyu": "gürültüyü",
    "hafifce": "hafifçe", "henuz": "henüz", "hiz": "hız",
    "his": "his", "hissi": "hissi",
    "icin": "için", "icindir": "içindir", "icinde": "içinde",
    "ice": "içe", "iddia": "iddia", "iki": "iki", "ince": "ince",
    "indigi": "indiği", "isaret": "işaret", "isaretliyse": "işaretliyse",
    "isigi": "ışığı", "isigin": "ışığın", "isik": "ışık",
    "isikta": "ışıkta", "islem": "işlem", "islemi": "işlemi",
    "islemler": "işlemler", "islenir": "işlenir", "islenmez": "işlenmez",
    "ister": "ister", "istiyorsaniz": "istiyorsanız",
    "izlenimi": "izlenimi",
    "kademelenir": "kademelenir", "kademeli": "kademeli",
    "kadraj": "kadraj", "kadraja": "kadraja", "kagidi": "kağıdı",
    "kagit": "kağıt", "kaldigi": "kaldığı", "kaldir": "kaldır",
    "kaldirildi": "kaldırıldı", "kaldirip": "kaldırıp",
    "kaldirir": "kaldırır", "kaldirma": "kaldırma",
    "kaldirmak": "kaldırmak", "kalinlik": "kalınlık", "kalir": "kalır",
    "kanalin": "kanalın", "kanalini": "kanalını",
    "kanallar": "kanallar", "kanallara": "kanallara",
    "kanallari": "kanalları", "kanallarinin": "kanallarının",
    "kapaliyken": "kapalıyken", "kapatir": "kapatır",
    "karakteristik": "karakteristik", "karartir": "karartır",
    "karistirilacak": "karıştırılacak", "kategoriler": "kategoriler",
    "katina": "katına", "katkisi": "katkısı",
    "katmani": "katmanı", "katmanindan": "katmanından",
    "katmanlari": "katmanları", "kaydedildi": "kaydedildi",
    "kaydedilecek": "kaydedilecek", "kaydedilemedi": "kaydedilemedi",
    "kaydedilmis": "kaydedilmiş", "kaydettiginiz": "kaydettiğiniz",
    "kaydirir": "kaydırır", "kaydirma": "kaydırma",
    "kaydirmalari": "kaydırmaları", "kaydirmasi": "kaydırması",
    "kayitli": "kayıtlı", "kayma": "kayma", "kaymasi": "kayması",
    "kaynaklarin": "kaynakların",
    "kaynaklarindan": "kaynaklarından", "kazanci": "kazancı",
    "kenardan": "kenardan", "kenarinin": "kenarının",
    "kenarlara": "kenarlara", "kenarlarda": "kenarlarda",
    "kenarlari": "kenarları", "kenarlarini": "kenarlarını",
    "kesilme": "kesilme", "keskin": "keskin",
    "keskinlestirilmez": "keskinleştirilmez", "kimyada": "kimyada",
    "kirliligi": "kirliliği", "kirmizi": "kırmızı",
    "kirmizidir": "kırmızıdır", "kirpilan": "kırpılan",
    "kirpma": "kırpma", "kitaplik": "kitaplık",
    "kitapliga": "kitaplığa", "kivrilir": "kıvrılır",
    "kizilotesi": "kızılötesi", "klasik": "klasik", "klasor": "klasör",
    "klasordeki": "klasördeki", "klasorleri": "klasörleri",
    "klasorun": "klasörün", "klipleme": "kırpılma",
    "kliplenmis": "kırpılmış", "kodla": "kodla",
    "komsu": "komşu", "komsulariyla": "komşularıyla",
    "kontrasti": "kontrastı", "kontrastin": "kontrastın",
    "kontrastini": "kontrastını", "kontrastli": "kontrastlı",
    "konumu": "konumu", "konumunu": "konumunu", "koru": "koru",
    "koruma": "koruma", "korur": "korur", "koruyarak": "koruyarak",
    "koyu": "koyu", "koyulastirir": "koyulaştırır",
    "koyultup": "koyultup", "kremlestirir": "kremleştirir",
    "kromatik": "kromatik", "kucuk": "küçük", "kucultur": "küçültür",
    "kullanilan": "kullanılan", "kullanilir": "kullanılır",
    "kullanilmaz": "kullanılmaz", "kullanin": "kullanın",
    "kurtarma": "kurtarma", "kutusuna": "kutusuna",
    "laboratuvari": "laboratuvarı", "lardan": "lardan", "lari": "ları",
    "leke": "leke", "lenslerde": "lenslerde",
    "lenslerinin": "lenslerinin", "lif": "lif", "lineer": "lineer",
    "maskeleriyle": "maskeleriyle", "maskesi": "maskesi",
    "maskesiz": "maskesiz", "maskeye": "maskeye", "maskeyi": "maskeyi",
    "mavi": "mavi", "maviden": "maviden", "mavimsidir": "mavimsidir",
    "merkeze": "merkeze", "merkezden": "merkezden",
    "merkezi": "merkezi", "metalik": "metalik", "mevcut": "mevcut",
    "minyatur": "minyatür", "misiniz": "misiniz", "monokrom": "monokrom",
    "monoton": "monoton", "mor": "mor",
    "ndan": "ndan", "negatifte": "negatifte", "net": "net",
    "noktalarini": "noktalarını", "noktasini": "noktasını",
    "noktayi": "noktayı", "normallendiginden": "normallendiğinden",
    "notr": "nötr", "notrdur": "nötrdür",
    "odak": "odak", "okunamadi": "okunamadı", "olabilir": "olabilir",
    "olanlar": "olanlar", "olanlara": "olanlara", "olarak": "olarak",
    "olcegi": "ölçeği", "olceklerde": "ölçeklerde",
    "olcekli": "ölçekli", "olcutu": "ölçütü", "oldugu": "olduğu",
    "olmasidir": "olmasıdır", "olmasiyla": "olmasıyla",
    "olmayan": "olmayan", "olmaz": "olmaz", "olsun": "olsun",
    "olur": "olur", "olusmasini": "oluşmasını", "olusmaz": "oluşmaz",
    "olusturur": "oluşturur", "olusur": "oluşur", "omuz": "omuz",
    "once": "önce", "onceki": "önceki", "onizleme": "önizleme",
    "onlar": "onlar", "onune": "önüne", "orana": "orana",
    "oranda": "oranda", "orani": "oranı", "oransal": "oransal",
    "orijinali": "orijinali", "ortusur": "örtüşür",
    "otomatik": "otomatik",
    "parlak": "parlak", "parlakligi": "parlaklığı",
    "parlakligin": "parlaklığın", "parlakligini": "parlaklığını",
    "parlaklik": "parlaklık", "parlama": "parlama",
    "parlatir": "parlatır", "paylasilir": "paylaşılır",
    "piksel": "piksel", "pozitif": "pozitif", "pozlama": "pozlama",
    "pozlamadan": "pozlamadan", "procedurel": "yordamsal",
    "profil": "profil", "profili": "profili", "profilini": "profilini",
    "projesini": "projesini", "projeye": "projeye",
    "projeyi": "projeyi",
    "radyal": "radyal", "rastgele": "rastgele", "rehber": "rehber",
    "rehberini": "rehberini", "rehberleri": "rehberleri",
    "renge": "renge", "rengi": "rengi", "renginin": "renginin",
    "renklere": "renklere", "renkleri": "renkleri",
    "renklerin": "renklerin", "renkli": "renkli",
    "renklidir": "renklidir", "renksiz": "renksiz", "resim": "resim",
    "sacilmasi": "saçılması", "saciimayi": "saçılmayı",
    "saglar": "sağlar", "sag": "sağ", "saklar": "saklar",
    "sari": "sarı", "sayiliyor": "sayılıyor", "sayisi": "sayısı",
    "sayisini": "sayısını", "sec": "seç", "secici": "seçici",
    "secilen": "seçilen", "secili": "seçili", "secin": "seçin",
    "sekiz": "sekiz", "sekillendirir": "şekillendirir",
    "serbest": "serbest", "serbestce": "serbestçe",
    "serigrafi": "serigrafi", "serit": "şerit", "seride": "şeride",
    "sert": "sert", "sertlestirir": "sertleştirir",
    "sertlik": "sertlik", "sicak": "sıcak", "sicakligi": "sıcaklığı",
    "sicakligini": "sıcaklığını", "sicaklik": "sıcaklık",
    "siddet": "şiddet", "siddeti": "şiddeti", "sifirla": "sıfırla",
    "sifirlandi": "sıfırlandı", "sifirlar": "sıfırlar",
    "sigdir": "sığdır", "sikismasi": "sıkışması",
    "sikismis": "sıkışmış", "sil": "sil", "siler": "siler",
    "silindi": "silindi", "silinemedi": "silinemedi",
    "silinse": "silinse", "silinsin": "silinsin",
    "sinirini": "sınırını", "sinirlarini": "sınırlarını",
    "sira": "sıra", "sirala": "sırala", "siralama": "sıralama",
    "sirayi": "sırayı", "sis": "sis", "siyah": "siyah",
    "siyahi": "siyahı", "siyahlar": "siyahlar",
    "siyahlari": "siyahları", "sizan": "sızan", "sizinti": "sızıntı",
    "soguk": "soğuk", "soldan": "soldan", "soluk": "soluk",
    "sonuk": "sönük", "sonucu": "sonucu", "surukleyerek": "sürükleyerek",
    "surukleyin": "sürükleyin", "surukleyip": "sürükleyip",
    "taban": "taban", "tablosunu": "tablosunu", "takilan": "takılan",
    "taklit": "taklit", "tamamini": "tamamını", "tane": "tane",
    "tanecikli": "tanecikli", "tanesi": "tanesi", "tanimli": "tanımlı",
    "tara": "tara", "taranamadi": "taranamadı", "taranir": "taranır",
    "taranmis": "taranmış", "tasinabilir": "taşınabilir",
    "tasinacak": "taşınacak", "tasindi": "taşındı", "tasir": "taşır",
    "tasiyin": "taşıyın", "tek": "tek", "teknik": "teknik",
    "tekrarlanabilir": "tekrarlanabilir", "temel": "temel",
    "temizlenemedi": "temizlenemedi", "ten": "ten", "tepkisi": "tepkisi",
    "ters": "ters", "tersine": "tersine", "tiklama": "tıklama",
    "tiklamak": "tıklamak", "tiklayarak": "tıklayarak",
    "tonlarda": "tonlarda", "tonlari": "tonları",
    "tonlarini": "tonlarını", "tonlara": "tonlara", "tonu": "tonu",
    "tonunu": "tonunu", "toplamindan": "toplamından", "toplar": "toplar",
    "toz": "toz", "tum": "tüm", "tumunu": "tümünü", "turde": "türde",
    "turu": "türü", "turkuaz": "turkuaz", "turuncu": "turuncu",
    "tuvaldeki": "tuvaldeki",
    "uclardaki": "uçlardaki", "ufuk": "ufuk", "uretilemedi": "üretilemedi",
    "uretilir": "üretilir", "ustune": "üstüne", "uyan": "uyan",
    "uygula": "uygula", "uygulamak": "uygulamak",
    "uygulanacak": "uygulanacak", "uygulandi": "uygulandı",
    "uygulanir": "uygulanır", "uygular": "uygular",
    "uzaklastir": "uzaklaştır", "uzerindeki": "üzerindeki",
    "uzunluk": "uzunluk",
    "varsa": "varsa", "varsayilana": "varsayılana",
    "varsayiliyor": "varsayılıyor", "verir": "verir", "veya": "veya",
    "yakalanmamis": "yakalanmamış", "yakin": "yakın",
    "yakinlastir": "yakınlaştır", "yalnizca": "yalnızca",
    "yanlis": "yanlış", "yansimasindan": "yansımasından",
    "yapar": "yapar", "yapin": "yapın",
    "yapistirildi": "yapıştırıldı", "yapmaz": "yapmaz",
    "yaratici": "yaratıcı", "yardim": "yardım",
    "yardimcisidir": "yardımcısıdır", "yaricap": "yarıçap",
    "yatay": "yatay", "yayar": "yayar", "yayilan": "yayılan",
    "yayildigi": "yayıldığı", "yayilimi": "yayılımı",
    "yayilir": "yayılır", "yayilma": "yayılma", "yazar": "yazar",
    "yazildi": "yazıldı", "yeni": "yeni", "yeniden": "yeniden",
    "yerde": "yerde", "yerine": "yerine", "yerlesik": "yerleşik",
    "yerel": "yerel", "yesil": "yeşil", "yesile": "yeşile",
    "yigina": "yığına", "yinele": "yinele", "yok": "yok",
    "yolunu": "yolunu", "yon": "yön", "yonlu": "yönlü", "yonu": "yönü",
    "yorumlar": "yorumlar", "yuklemede": "yüklemede",
    "yuklenemedi": "yüklenemedi", "yuklenmedi": "yüklenmedi",
    "yukleniyor": "yükleniyor", "yuksek": "yüksek",
    "yukselir": "yükselir", "yukselmis": "yükselmiş",
    "yumusak": "yumuşak", "yumusakligi": "yumuşaklığı",
    "yumusaktir": "yumuşaktır", "yumusar": "yumuşar",
    "yumusatir": "yumuşatır", "yumusatma": "yumuşatma",
    "yuvarlaklik": "yuvarlaklık", "yuz": "yüz", "yuzey": "yüzey",
    "yogunluk": "yoğunluk",
    "zayiflatilamaz": "zayıflatılamaz", "zaten": "zaten",
    # --- ikinci gecis: ilk taramada gozden kacanlar ---
    "ac": "aç", "aci": "açı", "alani": "alanı", "alinacak": "alınacak",
    "baska": "başka", "bazi": "bazı", "birakma": "bırakma",
    "bulundugu": "bulunduğu", "carki": "çarkı", "cikis": "çıkış",
    "degisince": "değişince", "genislik": "genişlik",
    "gorunumden": "görünümden", "gunluklerinin": "günlüklerinin",
    "hakkinda": "hakkında", "kadari": "kadarı", "klasoru": "klasörü",
    "klasorunu": "klasörünü", "kullanilanlar": "kullanılanlar",
    "sayac": "sayaç", "uc": "uç", "uygulamayi": "uygulamayı",
    "varsayildi": "varsayıldı", "yukseklik": "yükseklik",
    "yumusaklik": "yumuşaklık", "acilan": "açılan", "acilir": "açılır",
    "kapanir": "kapanır", "yazilir": "yazılır", "okunur": "okunur",
    "secmek": "seçmek", "secim": "seçim", "secimi": "seçimi",
    "gecin": "geçin", "gecer": "geçer", "birakildi": "bırakıldı",
    "calisma": "çalışma", "calismaz": "çalışmaz", "kapali": "kapalı",
    "acikca": "açıkça", "gectigi": "geçtiği", "dogrudan": "doğrudan",
    "sagda": "sağda", "solda": "solda", "asagida": "aşağıda",
    "yukarida": "yukarıda", "sonrasinda": "sonrasında",
    "oncesinde": "öncesinde", "disari": "dışarı", "iceri": "içeri",
    "yapistir": "yapıştır", "kopyala": "kopyala", "tarif": "tarif",
    "egriler": "eğriler", "acildi": "açıldı", "acilan": "açılan",
    "karsilastirma": "karşılaştırma", "yanyana": "yan yana",
    "surgu": "sürgü", "bolunmus": "bölünmüş", "orijinal": "orijinal",
    "sinematik": "sinematik", "laboratuvar": "laboratuvar",
    "aktarim": "aktarım", "gecerli": "geçerli", "onceden": "önceden",
    "kaydirici": "kaydırıcı", "tusu": "tuşu", "tuslari": "tuşları",
    # --- basliklar / ozel adlar ---
    "anamorfik": "anamorfik", "aberasyon": "aberasyon",
    "beyazlarin": "beyazların", "kalite": "kalite",
    "vignette": "vignette", "posterize": "posterize",
}


def convert_word(word: str) -> str:
    """Bir kelimeyi dogru yazimina cevirir; buyuk/kucuk duzenini korur."""
    fixed = WORDS.get(word.lower())
    if fixed is None:
        return word
    if word.isupper() and len(word) > 1:
        return fixed.upper().replace("I", "I").replace("i", "İ")
    if word[0].isupper():
        head = fixed[0]
        head = "İ" if head == "i" else head.upper()
        return head + fixed[1:]
    return fixed


#: Bicim yer tutucusu: `{ad}`, `{sayac}`, `{0}`, `{name!r}` ...
_PLACEHOLDER = re.compile(r"\{[^{}]*\}")


def convert_text(text: str) -> str:
    """Metindeki kelimeleri cevirir; **yer tutuculara dokunmaz**.

    `{ad}` veya `{sayac}` gibi bicim alanlarini cevirmek dizgiyi
    calismaz hale getirirdi: `str.format` ve f-string alan adlari ile
    ad sablonu belirtecleri koddaki ASCII yazimla eslesmek zorunda.
    """
    out: list[str] = []
    cursor = 0
    for match in _PLACEHOLDER.finditer(text):
        out.append(_convert_words(text[cursor:match.start()]))
        out.append(match.group(0))      # yer tutucu aynen kalir
        cursor = match.end()
    out.append(_convert_words(text[cursor:]))
    return "".join(out)


def _convert_words(chunk: str) -> str:
    return re.sub(r"[A-Za-zçğıöşüÇĞİÖŞÜ]+",
                  lambda m: convert_word(m.group(0)), chunk)
